service: todolist-serverless
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:REGION, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}

functions:
  - ${file(./functions/get/route.yml)}
  - ${file(./functions/post/route.yml)}
  - ${file(./functions/delete/route.yml)}
  - ${file(./functions/put/route.yml)}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-plugin
  - serverless-esbuild

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 2 # Number of versions to keep
